# Generated by Django 6.1.2 on 2026-10-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('images', models.JSONField(blank=True, default=list)),
                ('form_factor', models.CharField(blank=True, max_length=100)),
                ('sim_count', models.CharField(blank=True, max_length=100)),
                ('sim_format', models.CharField(blank=True, max_length=100)),
                ('network_generation', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('display_type', models.CharField(blank=True, max_length=100)),
                ('screen_diagonal', models.CharField(blank=True, max_length=50)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('refresh_rate', models.CharField(blank=True, max_length=50)),
                ('processor', models.CharField(blank=True, max_length=200)),
                ('cpu_cores', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=50)),
                ('main_camera_modules', models.CharField(blank=True, max_length=20)),
                ('main_camera', models.CharField(blank=True, max_length=100)),
                ('main_camera_aperture', models.CharField(blank=True, max_length=100)),
                ('stabilization', models.CharField(blank=True, max_length=100)),
                ('video_recording', models.CharField(blank=True, max_length=200)),
                ('front_camera_modules', models.CharField(blank=True, max_length=20)),
                ('front_camera', models.CharField(blank=True, max_length=100)),
                ('front_camera_aperture', models.CharField(blank=True, max_length=100)),
                ('camera_features', models.TextField(blank=True)),
                ('multimedia', models.TextField(blank=True)),
                ('organizer', models.TextField(blank=True)),
                ('wireless', models.CharField(blank=True, max_length=300)),
                ('navigation', models.CharField(blank=True, max_length=300)),
                ('interfaces', models.CharField(blank=True, max_length=200)),
                ('features', models.CharField(blank=True, max_length=300)),
                ('sensors', models.TextField(blank=True)),
                ('security', models.CharField(blank=True, max_length=200)),
                ('equipment', models.CharField(blank=True, max_length=300)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('body_features', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('warranty_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
