from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=500)
    images = models.JSONField(default=list, blank=True)
    form_factor = models.CharField(max_length=100, blank=True)
    sim_count = models.CharField(max_length=100, blank=True)
    sim_format = models.CharField(max_length=100, blank=True)
    network_generation = models.CharField(max_length=100, blank=True)
    os = models.CharField(max_length=100, blank=True)
    display_type = models.CharField(max_length=100, blank=True)
    screen_diagonal = models.CharField(max_length=50, blank=True)
    screen_resolution = models.CharField(max_length=50, blank=True)
    refresh_rate = models.CharField(max_length=50, blank=True)
    processor = models.CharField(max_length=200, blank=True)
    cpu_cores = models.CharField(max_length=50, blank=True)
    storage = models.CharField(max_length=50, blank=True)
    main_camera_modules = models.CharField(max_length=20, blank=True)
    main_camera = models.CharField(max_length=100, blank=True)
    main_camera_aperture = models.CharField(max_length=100, blank=True)
    stabilization = models.CharField(max_length=100, blank=True)
    video_recording = models.CharField(max_length=200, blank=True)
    front_camera_modules = models.CharField(max_length=20, blank=True)
    front_camera = models.CharField(max_length=100, blank=True)
    front_camera_aperture = models.CharField(max_length=100, blank=True)
    camera_features = models.TextField(blank=True)
    multimedia = models.TextField(blank=True)
    organizer = models.TextField(blank=True)
    wireless = models.CharField(max_length=300, blank=True)
    navigation = models.CharField(max_length=300, blank=True)
    interfaces = models.CharField(max_length=200, blank=True)
    features = models.CharField(max_length=300, blank=True)
    sensors = models.TextField(blank=True)
    security = models.CharField(max_length=200, blank=True)
    equipment = models.CharField(max_length=300, blank=True)
    condition = models.CharField(max_length=50, blank=True)
    dimensions = models.CharField(max_length=100, blank=True)
    weight = models.CharField(max_length=50, blank=True)
    color = models.CharField(max_length=50, blank=True)
    body_features = models.CharField(max_length=200, blank=True)
    manufacturer = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)
    warranty_months = models.PositiveSmallIntegerField(null=True, blank=True)
    barcode = models.CharField(max_length=50, blank=True)
    note = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
